### PR TITLE
Add LittleCMS2 support.

### LINKED ISSUE #58: Require the LittleCMS library?
It appears that the conda `pillow` package does not specify its dependence on the [LittleCMS](http://www.littlecms.com/) library, so attempting to use `PIL.ImageCMS` results in an error.  Is it possible to get this dependency included with pillow?  `recipe/build.sh` has the commented line `# export LCMS_ROOT=None`, so apparently some thought was put into this in the past.

### PR DESCRIPTION
**Pull request by pkgw**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #58. AFAICT, this hasn't happened simply just because no one has gotten around to it?

### CODE REVIEW

**Comment by pkgw** [comment]
@conda-forge/core Many errors about `gcc` not being found on platforms like stock Linux. Looking at the builds that did succeed, I think setuptools 48 is breaking this? The macOS build is succeeding with setuptools 48, and the Windows errors are different, so I think it might only be Linux.

**Comment by ocefpaf** [comment]
Yep. Older setuptools fixes it on Linux. The problem on Windows is b/c we are using an older libtiff there due to #69. Not sure if we solved that or not.

**Comment by pkgw** [comment]
The changelog for setuptools 49.1.0 (cf. conda-forge/setuptools-feedstock#153) says that it reverts the distutils bundling that looks like the likely cause of the Linux issues, so we might have to wait a bit longer for that to shake out. No rush here, though.

**Comment by patricksnape** [comment]
@conda-forge-admin please rerender

**Comment by patricksnape** [comment]
Looks like we have package conflicts for libtiff 4.0 on Windows?

**Comment by pkgw** [comment]
Yeah, and I ran into other issues with the libtiff 4.1 branch of the Windows builds. (See commit message.) Given that this feature seemingly isn't urgent, I just didn't enable LCMS for Windows, maintaining the status quo.

With that taken care of, shall we go ahead and merge?

**Comment by kmilos** [comment]
#69 was addressed by https://github.com/conda-forge/libtiff-feedstock/pull/51 AFAIK

**Comment by kmilos** [comment]
Can we try to [bring back](https://github.com/conda-forge/pillow-feedstock/commit/39bafc2ed0fc72d3794ce8b0e9e53a6d8b41dc23) lcms2 support in Pillow please?

**Comment by pkgw** [comment]
@kmilos Sure. Would you feel comfortable preparing a pull request yourself?

**Comment by kmilos** [comment]
Sure, will try in the coming days.

**Comment by kmilos** [comment]
Ok, was quicker than I thought: https://github.com/conda-forge/pillow-feedstock/pull/89

**Pull request merged**
