### PR TITLE
7.0.0 with libtiff 4.0 (windows only) and 4.1 (all arch)

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by patricksnape** [comment]
@conda-forge/core - This looks good to me but since Pillow is such an important package in the ecosystem would love another set of eyeballs to ensure this won't break things

**Comment by hmaarrfk** [comment]
The two py38 (and presumably other packages too) have different hashes
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=107847&view=logs&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=d66ed8ca-07ff-5419-c5d1-5e21fa500bb4&l=1334

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=107847&view=logs&j=7df5a329-fcdb-5857-5720-a5dae94c0641&t=a71eafb0-3238-5beb-cebc-fe4d16b695d4&l=1332

We should be ok

**Comment by patricksnape** [comment]
It looks to me like your libtiff patch is going to work out? So maybe we just reopen the other MR and don't both with such a complex build matrix if the patched libtiff 4.1 works?

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=107881&view=logs&j=2cc45e14-23e3-52d7-b33a-8c2744410b97&t=21c44aa7-1ae3-5312-cacc-7f19fefc82f4

**Comment by hmaarrfk** [comment]
Is there any other library we want to test against

**Comment by scopatz** [comment]
This LGTM

**Comment by patricksnape** [comment]
Merging

**Pull request merged**
