### PR TITLE
pillow v8.4.0 (redux) & rebuild for python310 

### PR DESCRIPTION
**Pull request by h-vetinari**
Continuing from #99

OSX builds were running into
```
/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include/AvailabilityMacros.h:244:5: error: 'TARGET_OS_OSX' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_OSX]
#if TARGET_OS_OSX
```
~so let's add it (quick search on cf showed similar commits e.g. [here](https://github.com/conda-forge/re2-feedstock/commit/ca29a134d361f46ac6f6cd775362557481b91a74)).~

due to https://github.com/python-pillow/Pillow/pull/5624.

Fixes #99

### CODE REVIEW

**Comment by h-vetinari** [comment]
OK, I think https://github.com/python-pillow/Pillow/pull/5624 broke the build here.

Conda-forge sets up everything with the 10.9 SDK, but Pillow (since that PR) picks up the SDK for 11.1 from the VM, and obviously things start going wrong afterwards.

**Comment by h-vetinari** [comment]
@conda-forge/pillow PTAL
#99 has been blocked for a while - I ended up looking at this because I had seen that pillow is one of the biggest current blockers for the 3.10 migration (though not sure where the resolver of the migration bot gets hung up about it).

Once I got the build passing I decided to add the migration here as well, and things went fine. :)

**Comment by beckermr** [comment]
Thanks for the work here @h-vetinari!

**Comment by h-vetinari** [comment]
> Can you add yourself as a maintainer here too?

Done. I don't have much expertise with the image stack, but will try to help where possible.

**Comment by ocefpaf** [comment]
Thanks @h-vetinari for the fix and @beckermr for the merge!

**Pull request merged**
