### PR TITLE
Rebuild for python311

### PR DESCRIPTION
**Pull request by dopplershift**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Interesting error from one of [the macOS builds (not Python 3.11)]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=597868&view=logs&jobId=c35410bf-a820-56fd-e231-d3cd4bead63c&j=c35410bf-a820-56fd-e231-d3cd4bead63c&t=b92b255f-9dfe-5c14-4730-460f7a671001 ):

```
/Users/runner/miniforge3/conda-bld/pillow_1666909299541/_build_env/etc/conda/activate.d/activate_z-cross-python_osx-arm64.sh: line 1: ��: No such file or directory
```

**Comment by h-vetinari** [comment]
Things seem to be fine now. LGTM

**Review by h-vetinari — APPROVED** [review]

**Comment by jakirkham** [comment]
Yeah restarted the build after Isuru pulled the problematic package

**Comment by djhoese** [comment]
I could be missing something but the status page (https://conda-forge.org/status/) shows this as unsolvable now and might be stopping dependents from migrating.

**Comment by h-vetinari** [comment]
> I could be missing something but the status page (https://conda-forge.org/status/) shows this as unsolvable now and might be stopping dependents from migrating.

You're right, but the migrator should eventually try again, realize it's been done already, and mark it as complete. These sort of restarts don't happen on every run though, and with the migration in full swing, it might take a little.

**Pull request merged**
