### PR TITLE
Test jpeg 9b

### PR DESCRIPTION
**Pull request by ocefpaf**
Just testing.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Based on this test we should either downgrade everything to `xz 5.0.5` and `jpeg 8d` or update our Pythons 3.4 ad 3.5 :unamused: 

I would love to have the latter, but the former seems to be the only one feasible.

@pelson and @jakirkham if you agree I can start re-building this against `jpeg 8d` and `xz 5.0.5` today.

**Comment by pelson** [comment]
```
conda execute list_deps.py defaults --packages libtiff --dependencies jpeg --platform linux-64
Fetching package metadata: ....
libtiff 4.0.2 1 linux-64           : jpeg 8d
libtiff 4.0.6 0 linux-64           : jpeg 8d
libtiff 4.0.6 1 linux-64           : jpeg 8d
```

And yet conda is happily resolving the default's libtiff with jpeg 9... I really don't follow what is going on.

```
The following NEW packages will be INSTALLED:

    freetype:   2.5.5-0       defaults                                        
    jpeg:       9b-0          conda-forge                                     
    libpng:     1.6.17-0      defaults                                        
    libtiff:    4.0.2-0       defaults                                        
    openssl:    1.0.2g-0      defaults                                        
    pillow:     3.2.0-py34_0  file:///feedstock_root/build_artefacts/linux-64/
    pip:        8.1.1-py34_1  defaults                                        
    python:     3.4.4-0       defaults                                        
    readline:   6.2-2         defaults                                        
    setuptools: 20.7.0-py34_0 defaults                                        
    sqlite:     3.9.2-0       defaults                                        
    tk:         8.5.18-0      defaults                                        
    wheel:      0.29.0-py34_0 defaults                                        
    xz:         5.0.5-1       defaults                                        
    zlib:       1.2.8-0       conda-forge                                     

===== testing package: pillow-3.2.0-py34_0 =====
import: 'PIL'
import: 'PIL.Image'
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/test-tmp_dir/run_test.py", line 28, in <module>
    import PIL.Image
  File "/opt/conda/envs/_test/lib/python3.4/site-packages/PIL/Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory
```

I suspect we are seeing a conda/conda-build bug here, but I'm trying to get my head around it to reproduce easily..

**Comment by jakirkham** [comment]
> Based on this test we should either downgrade everything to `xz 5.0.5` and `jpeg 8d`...

This is the only path forward AFAICT. Otherwise we have a bunch of broken packages we can't really seem to fix. I'm not sure I understand the problems that are occurring, but we were using those old versions fine for awhile. Maybe it is time to try going back to those versions in the stack.

**Comment by pelson** [comment]
Things I have ruled out:

 * jpeg is correctly expressing its dependencies. otool and ldd tell me there are no unexpected dependencies.

 * Rebuilding with circle. Builds fine (with conda-forge's libtiff)

It appears that this has now been fixed by Continuum removing their [badly pinned libtiff](https://github.com/ContinuumIO/anaconda-issues/issues/762). @ocefpaf - could you please re-open this PR?

**Comment by pelson** [comment]
> It appears that this has now been fixed by Continuum removing their badly pinned libtiff.

or not even that - it is still there... too many moving parts to understand what has happened here, but suffice to say, we appear to be getting on top of it somehow.

**Comment by ocefpaf** [comment]
I forgot about this one yesterday when re-build everything from the ground up with `jpeg 9b`. Pillow is now compatible with the rest of conda-forge (see #4). However, if someone tries to install something from the default channel it is pinned against `jpeg 8d`, or for some weird reason conda downgrades `jpeg`, then we will have broken packages.

**Comment by jakirkham** [comment]
> ...too many moving parts to understand what has happened here...

Completely agree. I'm really not sure what happened or will reoccur.

> ...we appear to be getting on top of it somehow.

I guess, but without understanding why it is bit worrisome still.

**Comment by ocefpaf** [comment]
I can explain better during the next meeting, but here is the gist of it (omitting some cases where conda solver failed us).

1. I added `libxml2`, which depended on `libzma` (`xz`), to satisfy `libspatialite` (an optional dependency of `gdal`). `libxml2` was failing on OS X with complaining about the API version of `xz`.

2. I then added an updated version of `xz` (`5.2.2`) to fix `libxml2`/`libspatialite` on OS X. Sadly that broken all Python 3 builds because both Python 3.4 and 3.5 were built against `xz 5.0.5`.

3. The `jpeg` issue (version `8d` vs `9b`) was caught in the crossfire because `libtiff` depends on both `jpeg` and `xz`. That means building `pillow` against `jpeg 8b` would make it pull an older `libtiff`, older `xz`, and make it non-compatible with the packages compiled against `jpeg 9b`. While building `pillow` against `jpeg 9b` would make it pull newer `libtiff`, newer `xz`, and make in incompatible with Python 3.

4. I realized that all the parts to use `jpeg 9b` where already in `conda-forge`, but the parts to use `xz 5.2.2`, the one incompatible with Python 3, are not! (That part is the Python 3 recipe.)

5. I re-built everything pinning against `jpeg 9b` and `xz 5.0.5` so Python 3 is working again everrwhere.

Things to consider for the future:

- Before we merge the Python 3.5 recipe I would like to put `xz 5.2.2` back on the channel and build Python against it.

- If the default channel has anything pinned against `jpeg 8b` that package will not play along conda-forge packages.

**Pull request closed without merging**
