### PR TITLE
Bump

### PR DESCRIPTION
**Pull request by ocefpaf**
```shell
3.3.1 (2016-08-18)
------------------

- Fix C90 compilation error for Tcl / Tk rewrite #2033
  [matthew-brett]

- Fix image loading when rotating by 0 deg #2052
  [homm]
```

### CODE REVIEW

**Comment by patricksnape** [comment]
Why is conda-inspect commented out? Can't see any build failures?

**Comment by ocefpaf** [comment]
> Why is conda-inspect commented out? Can't see any build failures?

Latest version of conda-build broke inspect. @msarahan was that fixed? I lost track of it.

**Comment by msarahan** [comment]
Should be fixed in conda build 2,but I don't know what the status is on rolling that out on conda forge.

**Comment by ocefpaf** [comment]
From [another build](https://circleci.com/gh/conda-forge/mpich-feedstock/20):

`conda-build-2.0.0          |           py35_0         260 KB  defaults`

```
For bug reporting instructions, please see:
<http://gcc.gnu.org/bugs.html>.
+ conda inspect linkages -n _test mpich
Traceback (most recent call last):
  File "/opt/conda/bin/conda-inspect", line 5, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build/main_inspect.py", line 172, in main
    default=config.prefix_length,
AttributeError: 'Config' object has no attribute 'prefix_length'
TESTS FAILED: mpich-3.2-2
```

**Comment by ocefpaf** [comment]
But...

```
The following packages will be DOWNGRADED due to dependency conflicts:

    conda-build: 2.0.0-py35_0 defaults --> 1.21.14-py35_0 defaults
```

Argh!

**Comment by patricksnape** [comment]
Yeah we had to force a downgrade on the latest conda-build for the time being due to a change of the API that was breaking `conda-build-all`.

**Pull request merged**
