### PR TITLE
Update to 5.0.0

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by hugovk** [comment]
@ocefpaf Thanks for this. Do you know when this will be available on conda?

**Comment by ocefpaf** [comment]
They are already available for conda-forge:

https://anaconda.org/conda-forge/pillow/files?version=5.0.0

**Comment by hugovk** [comment]
Great! I'm not a conda user myself, would you be able to advise on https://github.com/python-pillow/Pillow/issues/2945?

**Comment by ocefpaf** [comment]
Done! See https://github.com/python-pillow/Pillow/issues/2945#issuecomment-356908217

**Pull request merged**
