### PR TITLE
test #69

### PR DESCRIPTION
**Pull request by ocefpaf**
Testing to see if we can reproduce the failure from #69 in the CIs.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gillins do you know what may be wrong in the libtiff recipe that could cause this failure?

**Comment by gillins** [comment]
Hmmm... Do you know anything about tempfile.tif?
```
tempfile.tif: Cannot read TIFF header.
```

**Comment by gillins** [comment]
I think this is a bit suspect (something gone wrong after the `/M`) but can't see anything obviously wrong with `setup.py`:
```
/DNDEBUG /M-DHAVE_LIBTIFF -DPILLOW_VERSION="\"6.2.1\""
```

**Comment by ocefpaf** [comment]
> I think this is a bit suspect (something gone wrong after the `/M`) but can't see anything obviously wrong with `setup.py`:
> 
> ```
> /DNDEBUG /M-DHAVE_LIBTIFF -DPILLOW_VERSION="\"6.2.1\""
> ```

I rebased this against latest master to check if the new version fixed that but it seems that the issue remains :-(

**Comment by gillins** [comment]
@ocefpaf seems to be compiling OK now, just the tests failing.

**Comment by ocefpaf** [comment]
> @ocefpaf seems to be compiling OK now, just the tests failing.

I probably looked at the wrong logs. The test error is:

```
tempfile.tif: Cannot read TIFF header.
Traceback (most recent call last):
  File "D:\bld\pillow_1582740975412\test_tmp\run_test.py", line 8, in <module>
    im.load()
  File "D:\bld\pillow_1582740975412\_test_env\lib\site-packages\PIL\TiffImagePlugin.py", line 1070, in load
    return self._load_libtiff()
  File "D:\bld\pillow_1582740975412\_test_env\lib\site-packages\PIL\TiffImagePlugin.py", line 1182, in _load_libtiff
    raise OSError(err)
OSError: -2
```

I'll make a few tests with libtiff to see if I can fix that. Thanks @gillins!

**Comment by pkgw** [comment]
The relevant issue has been solved down in libtiff.

**Pull request closed without merging**
