### PR TITLE
update to 5.0.0

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by hugovk** [comment]
Pillow 5.0.0 rearranged the source directories, so you'll need to update the patch so it applies cleanly.

See https://pillow.readthedocs.io/en/5.0.0/releasenotes/5.0.0.html#source-layout-changes

Or alternatively, is the patch still needed?

**Comment by ocefpaf** [comment]
> Or alternatively, is the patch still needed?

Probably not. I'll send a PR to test this in a moment. Closing this for now.

**Comment by sannykr** [comment]
@hugovk @ocefpaf : Thanks

**Comment by TanayAarush** [comment]
Same here, I am using Anaconda Spyder 3.2.4, on Python 3.6.3, Pillow 5.0.0

I installed Pillow using "conda install -c anaconda pillow"
While using "from PIL import Image"
Facing the error :- "ImportError: DLL load failed: The specified module could not be found."

Trying various forums, reading various documents since last 2/3 days. But still the same error. Its painful. I don't know how to resolve it.

**Pull request closed without merging**
