### PR TITLE
Update to 3.3.0

### PR DESCRIPTION
**Pull request by ocefpaf**
```
Changelog (Pillow)
==================

3.3.0 (2016-07-01)
------------------

- Fixed enums for Resolution Unit and Predictor in TiffTags.py #1998
  [wiredfool]

- Fix issue converting P mode to LA #1986
  [didrix]
  
- Moved test_j2k_overflow to check_j2k_overflow, prevent DOS of our 32bit testing machines #1995
  [wiredfool]

- Skip CRC checks in PNG files when LOAD_TRUNCATED_IMAGES is enabled #1991
  [kkopachev]

- Added CMYK mode for opening EPS files #1826
  [radarhere]

- Docs: OSX build instruction clarification #1994
  [wiredfool]

- Docs: Filter comparison table #1993
  [homm]

- Removal of pthread based Incremental.c, new interface for file decoders/encoders to access the python file. Fixes assorted J2k Hangs. #1934
  [wiredfool]

- Skip unnecessary passes when resizing #1954
  [homm]

- Removed duplicate code in ImagePalette #1832
  [radarhere]

- test_imagecms: Reduce precision of extended info due to 32 bit machine precision #1990
  [AbdealiJK]
  
- Binary Tiff Metadata/ICC profile. #1988
  [wiredfool]
  
- Ignore large text blocks in PNG if LOAD_TRUNCATED_IMAGES is enabled #1970
  [homm]

- Replace index = index+1 in docs with +=1
  [cclauss]

- Skip extra 0xff00 in jpeg #1977
  [kkopachev]
  
- Use bytearray for palette mutable storage #1985
  [radarhere, wiredfool]

- Added additional uint modes for Image.fromarray, more extensive tests of fromarray #1984
  [mairsbw, wiredfool]

- Fix for program importing PyQt4 when PyQt5 also installed #1942
  [hugovk]

- Changed depends/install_*.sh urls to point to github pillow-depends repo #1983
  [wiredfool]
  
- Allow ICC profile from `encoderinfo` while saving PNGs #1909
  [homm]

- Fix integer overflow on ILP32 systems (32-bit Linux). #1975
  [lambdafu]

- Change function declaration to match Tcl_CmdProc type #1966
  [homm]

- Integer overflow checks on all calls to *alloc #1781
  [wiredfool]

- Change equals method on Image so it short circuits #1967
  [mattBoros]
 
- Runtime loading of TCL/TK libraries, eliminating build time dependency. #1932
  [matthew-brett]

- Cleanup of transform methods #1941
  [homm]

- Fix "Fatal Python error: UNREF invalid object" in debug builds #1936
  [wiredfool]

- Setup fixes for Alpine linux #1937
  [wiredfool]

- Split resample into horizontal + vertical passes #1933
  [homm]

- Box blur with premultiplied alpha #1914
  [homm]

- Add libimagequant support in quantize() #1889
  [rr-]

- Added internal Premultiplied luminosity (La) mode #1912
  [homm]

- Fixed point integer resample #1881
  [homm]

- Removed docs/BUILDME script #1924
  [radarhere]

- Moved comments to docstrings  #1926
  [hugovk]

- Include Python.h before wchar.h so _GNU_SOURCE is set consistently #1906
  [hugovk]

- Updated example decoder in documentation #1899
  [radarhere]

- Added support for GIF comment extension #1896
  [radarhere]

- Removed support for pre- 1.5.2 list form of Image info in Image.new #1897
  [radarhere]

- Fix typos in TIFF tags #1918
  [radarhere]

- Skip tests that require libtiff if it is not installed, fixes #1866
  [wiredfool]

- Skip test when icc profile is not available, fixes #1887
  [doko42]

- Make deprecated functions raise NotImplementedError instead of Exception. #1862, #1890
  [daniel-leicht, radarhere]

- Replaced os.system with subprocess.call in setup.py #1879
  [radarhere]

- Corrected Image show documentation #1886
  [radarhere]

- Added check for executable permissions to ImageShow #1880
  [radarhere]

- Fixed tutorial code and added explanation #1877
  [radarhere]

- Added OS X support for ImageGrab grabclipboard #1837
  [radarhere]

- Combined duplicate code in ImageTk #1856
  [radarhere]

- Added --disable-platform-guessing option to setup.py build extension, #1861
  [angeloc]

- Fixed loading Transparent PNGs with a transparent black color #1840
  [olt]

- Add support for LA mode in Image.fromarray #1865
  [pierriko]

- Make ImageFile load images in read-only mode #1864
  [hdante]

- Added _accept hook for XVThumbImagePlugin #1853
  [radarhere]

- Test TIFF with LZW compression #1855, TGA RLE file #1854
  [hugovk]

- Improved SpiderImagePlugin help text #1863
  [radarhere]

- Updated Sphinx project description #1870
  [radarhere]

- Remove support for Python 3.0 from _imaging.c #1851
  [radarhere]

- Jpeg qtables are unsigned chars #1814, #1921
  [thebostik]

- Added additional EXIF tags #1841, TIFF Tags #1821
  [radarhere]

- Changed documentation to refer to ImageSequence Iterator #1833
  [radarhere]

- Fix Fedora prerequisites in installation docs, depends script #1842
  [living180]

- Added _accept hook for PixarImagePlugin #1843
  [radarhere]

- Removed outdated scanner classifier #1823
  [radarhere]

- Combined identical error messages in _imaging #1825
  [radarhere]

- Added debug option for setup.py to trace header and library finding #1790
  [wiredfool]

- Fix doc building on travis #1820, #1844
  [wiredfool]

- Fix for DIB/BMP images #1813, #1847
  [wiredfool]

- Add PixarImagePlugin file extension #1809
  [radarhere]

- Catch struct.errors when verifying png files #1805
  [wiredfool]

- SpiderImagePlugin: raise an error when seeking in a non-stack file #1794
  [radarhere, jmichalon]

- Added Support for 2/4 bpp Tiff Grayscale Images #1789
  [zwhfly]

- Removed unused variable from selftest #1788
  [radarhere]

- Added warning for as_dict method (deprecated in 3.0.0) #1799
  [radarhere]

- Removed powf support for older Python versions #1784
  [radarhere]

- Health fixes #1625 #1903
  [radarhere]
```

### CODE REVIEW

**Comment by ocefpaf** [comment]
Windows `Environment: TARGET_ARCH=x86, CONDA_PY=34` is failing with:

```shell
C:\conda\conda-bld\work\Pillow-3.3.0>call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /Release /x86 
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.1\.
Targeting Windows 7 x86 Release
Single threaded build for windows
running build_ext
Traceback (most recent call last):
  File "setup.py", line 753, in <module>
    zip_safe=not debug_build(), )
  File "C:\conda\envs\_build\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\conda\envs\_build\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\conda\envs\_build\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\conda\envs\_build\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 521, in build_extensions
    ' using --disable-%s, aborting' % (f, f))
ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting
```

@msarahan, @patricksnape, and @gillins do you have any clue of what might be the issue here?

**Comment by patricksnape** [comment]
@ocefpaf Just got back from a conference - will be at my Windows PC tomorrow so can check then.

**Comment by ocefpaf** [comment]
No worries. We can merge this as-is and fixed the failure in another PR BTW.

**Comment by jakirkham** [comment]
Sounds like this issue ( https://github.com/conda-forge/pillow-feedstock/issues/9 ).

**Pull request merged**
