### PR TITLE
Pin to new freetype

### PR DESCRIPTION
**Pull request by ocefpaf**
Waiting on https://github.com/conda-forge/freetype-feedstock/pull/3

### CODE REVIEW

**Comment by pelson** [comment]
Seems reasonable to me. I'd merge 😉

**Comment by ocefpaf** [comment]
AppVeyor `TARGET_ARCH=x86` and `CONDA_PY=34` is failing with:

```shell
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-kmj7txjj-build\setup.py", line 767, in <module>
        zip_safe=not debug_build(), )
      File "C:\conda\envs\_build\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\conda\envs\_build\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\conda\envs\_build\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\conda\envs\_build\lib\site-packages\setuptools-20.7.0-py3.4.egg\setuptools\command\install.py", line 61, in run
      File "C:\conda\envs\_build\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "C:\conda\envs\_build\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\conda\envs\_build\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\conda\envs\_build\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "C:\conda\envs\_build\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\conda\envs\_build\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\conda\envs\_build\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-kmj7txjj-build\setup.py", line 512, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
    
    ----------------------------------------
Command "C:\conda\envs\_build\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-kmj7txjj-build\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\appveyor\AppData\Local\Temp\1\pip-fls7oyoo-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\appveyor\AppData\Local\Temp\1\pip-kmj7txjj-build\ 
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command. 
Command failed: C:\Windows\system32\cmd.exe /c call bld.bat
Command exited with code 1
```

**Comment by jakirkham** [comment]
This error is coming from Pillow. Weird as it should already have JPEG.

Pinged @msarahan to take a look at this. Maybe he knows what is happening here.

Going to also try restarting to see if we still get this error with `conda-build` 1.20.3.

**Comment by jakirkham** [comment]
Restarted. Here is the [old log]( https://ci.appveyor.com/project/conda-forge/pillow-feedstock/build/1.0.9 ) in case people are curious.

**Comment by jakirkham** [comment]
This is the closest issue ( https://github.com/python-pillow/Pillow/issues/1275 ) I saw on Pillow's repo. Maybe they have some advice for us. Pointed them here so maybe someone can suggest or try something.

**Comment by msarahan** [comment]
Sorry, no idea off the top of my head.  Make sure you have all the extra options set so that it looks for the libraries/headers in %LIBRARY_PREFIX%.  I don't know what those options are for Pillow, though - sorry.

**Comment by ocefpaf** [comment]
I will take a second look at this. I believe pillow has a way to hard-code those in `setup.py`, not sure...

**Comment by ocefpaf** [comment]
I will take a second look at this. I believe pillow has a way to hard-code those in `setup.py`, not sure...

**Comment by jakirkham** [comment]
So one of the devs at Pillow recommended adding the `--debug` flag. However, it is not in a release. So, we would need to add a patch with this commit ( https://github.com/python-pillow/Pillow/commit/80758e1bd7bf42ab6a62b63df57c386041e69bbd ).

**Comment by jakirkham** [comment]
So, this is going to merged when PR ( https://github.com/conda-forge/pillow-feedstock/pull/8 ) gets merged. We've ( @ocefpaf and I ) decided we are ok with the Windows failure for now because no one has time to fix it and the pinning is far worse. Plus the failure will help us remember to come back and take a look. It's not the ideal decision, but I don't really know what else to say. The pinning problem is just far worse right now. When someone gets a chance we should take a look at this Windows failure again.

**Pull request merged**
