### PR TITLE
WIP: Remove pinning of vs2015_runtime

### PR DESCRIPTION
**Pull request by jakirkham**
**DO NOT MERGE YET! THIS WILL BREAK WINDOWS PYTHON 3.5 BUILDS.**

Just getting this one ready. We ultimately do want to merge this, but not until issue ( https://github.com/conda-forge/staged-recipes/issues/666 ) is resolved.

### CODE REVIEW

**Comment by pelson** [comment]
I have just restarted AppVeyor, and believe this will now pass. Please merge when it goes green. :+1:

**Comment by pelson** [comment]
Maybe it wont go green though because of py34 x86: https://github.com/conda-forge/pillow-feedstock/issues/9

**Comment by patricksnape** [comment]
https://github.com/conda-forge/staged-recipes/issues/666 Should no longer be an issue as I believe @msarahan removed the broken runtime. I haven't look at #9 yet but it does seem frustrating.

**Comment by jakirkham** [comment]
Correct, this should be fine.

**Comment by jakirkham** [comment]
Yeah, issue ( https://github.com/conda-forge/pillow-feedstock/issues/9 ) already existed in `master` so every PR will hit that problem. Not sure why it exists now. When someone has time it might be worth digging into history here and at staged-recipes as I *believe* this was passing at some point.

**Pull request merged**
